## DO NOT EDIT THIS FILE MANUALLY
## THIS APPLIES THE PATCHES FROM THE PATCH DIRECTORY
## https://github.com/GRcraft/apply.sh

cd .
echo $PWD

for entry in ../patches/*.patch
do
    echo "Applying patch $entry"
    patch -p1 < $entry -t
done

git log
